feature/MM5-4920-generate_thumbnails_labels
Digizuite/configurations pull request #120
Opened 2023-07-18 11:21 UTC by zenkaeser

https://digizuite.atlassian.net/browse/MM5-4920

2023-07-18 11:51 UTC, Poiar requested changes

2023-07-18 11:51 UTC, Poiar commented on MM/5.8.0/config/media_manager_5/labels/Preview Asset.dcl
> +      default_translation = 'Træk skyderen for at vælge dit foretrukne miniaturebillede, og klik på \'Gem\''
```suggestion
      default_translation = 'Træk i slideren for at vælge dit foretrukne miniaturebillede. Klik derefter \'Gem\''
```

2023-07-18 11:51 UTC, Poiar commented on MM/5.8.0/config/media_manager_5/labels/Preview Asset.dcl
> +      default_translation = 'Vælg dit foretrukne miniaturebillede, og klik på \'Gem\', eller generer nyt'
```suggestion
      default_translation = 'Tryk på "Generer" indtil du finder et miniaturebillede du kan lide. Vælg det og tryk \'Gem\''
```

2023-08-03 07:22 UTC, Poiar requested changes

2023-08-03 07:22 UTC, Poiar commented on MM/5.8.0/config/media_manager_5/labels/Preview Asset.dcl
> +      default_translation = 'Genskabe'
```suggestion
      default_translation = 'Generer nye thumbnails'
```

2023-08-03 07:22 UTC, Poiar commented on MM/5.8.0/config/media_manager_5/labels/Preview Asset.dcl
> +      default_translation = 'Skift video thumbnail'
```suggestion
      default_translation = 'Skift thumbnail'
```

2023-08-03 07:22 UTC, Poiar commented on MM/5.8.0/config/media_manager_5/labels/Preview Asset.dcl
> +      default_translation = 'Change video thumbnail'
```suggestion
      default_translation = 'Change thumbnail'
```

2023-08-03 07:22 UTC, Poiar commented on MM/5.8.0/config/media_manager_5/labels/Preview Asset.dcl
> +      default_translation = 'Vælg dit foretrukne miniaturebillede, og klik på \'Gem\', eller genskabe muligheder'
```suggestion
      default_translation = 'Vælg dit foretrukne thumbnail, og klik på \'Gem\', ellers generer nye thumbnails'
```

2023-08-03 07:22 UTC, Poiar commented on MM/5.8.0/config/media_manager_5/labels/Preview Asset.dcl
> +      default_translation = 'Select your preferred thumbnail and click \'Save\', or re-generate options'
```suggestion
      default_translation = 'Select your preferred thumbnail and click \'Save\', or generate new thumbails'
```

2023-08-03 07:22 UTC, Poiar commented on MM/5.8.0/config/media_manager_5/labels/Preview Asset.dcl
> +      default_translation = 'Re-generate'
```suggestion
      default_translation = 'Generate new thumbnails'
```

2023-08-03 07:22 UTC, Poiar commented on MM/5.8.0/config/media_manager_5/labels/Preview Asset.dcl
> +      default_translation = 'Specifik ramme'
```suggestion
      default_translation = 'Specifikt stillbillede'
```

2023-08-03 07:22 UTC, Poiar commented on MM/5.8.0/config/media_manager_5/labels/Preview Asset.dcl
> +      default_translation = 'Tilfældig ramme'
```suggestion
      default_translation = 'Tilfældigt stillbillede'
```

2023-08-03 07:48 UTC, bbedigi requested changes

2023-08-03 07:48 UTC, bbedigi commented on MM/5.8.0/config/media_manager_5/labels/Asset List.dcl
> +      default_translation = 'Change thumbnails'
```suggestion
      default_translation = 'Change thumbnail'
```

2023-08-03 07:48 UTC, bbedigi commented on MM/5.8.0/config/media_manager_5/labels/Asset List.dcl
> +      default_translation = 'Skift thumbnails'
```suggestion
      default_translation = 'Skift thumbnail'
```

2023-08-03 07:51 UTC, bbedigi approved these changes

2023-08-03 07:51 UTC, Poiar approved these changes

2023-08-03 07:52 UTC, merged