feature/CCC-844 Added labels
Digizuite/configurations pull request #238
Opened 2023-11-06 14:57 UTC by Svane20

2023-11-07 09:05 UTC, Poiar requested changes

2023-11-07 09:05 UTC, Poiar commented on MM/5.8.0/config/media_manager_5/labels/Creative Cloud Connector.dcl
> +      default_translation = 'Åben dokumentet'
```suggestion
      default_translation = 'Åbn dokumentet'
```

2023-11-07 09:05 UTC, Poiar commented on MM/5.9.0/config/media_manager_5/labels/Creative Cloud Connector.dcl
> +      default_translation = 'Åben dokumentet'
```suggestion
      default_translation = 'Åbn dokumentet'
```

2023-11-09 09:00 UTC, MUlisse approved these changes

2023-11-09 09:02 UTC, merged