importer labels
Digizuite/configurations pull request #285
Opened 2024-01-09 16:06 UTC by andrii-moskalenko

2024-01-10 12:45 UTC, leon-thorsell-simonsen requested changes

2024-01-10 12:45 UTC, leon-thorsell-simonsen commented on MM/5.9.0/config/media_manager_5/labels/Settings.dcl
> +      default_translation = "Reject if combo doesn't exist"
```suggestion
      default_translation = "Afvis hvis combo ikke eksisterer"
```

2024-01-10 12:45 UTC, leon-thorsell-simonsen commented on MM/5.9.0/config/media_manager_5/labels/Settings.dcl
> +      default_translation = "Reject if combo doesn't exist"
```suggestion
      default_translation = "Afvis hvis combo ikke eksisterer"
```

2024-01-10 12:45 UTC, leon-thorsell-simonsen commented on MM/5.9.0/config/media_manager_5/labels/Settings.dcl
> +      default_translation = "Reject if combo doesn't exist"
```suggestion
      default_translation = "Reject if tree node doesn't exist"
```

2024-01-10 12:45 UTC, leon-thorsell-simonsen commented on MM/5.9.0/config/media_manager_5/labels/Settings.dcl
> +      default_translation = "Reject if combo doesn't exist"
```suggestion
      default_translation = "Afvis hvis trænoden ikke eksisterer"
```

2024-01-10 12:45 UTC, leon-thorsell-simonsen commented on MM/5.9.0/config/media_manager_5/labels/Settings.dcl
> +      default_translation = "Reject if tree doesn't exist"
```suggestion
      default_translation = "Afvis hvis trænoden ikke eksisterer"
```

2024-01-10 12:45 UTC, leon-thorsell-simonsen commented on MM/5.9.0/config/media_manager_5/labels/Settings.dcl
> +      default_translation = "Reject if tree doesn't exist"
```suggestion
      default_translation = "Reject if tree node doesn't exist"
```

2024-01-11 09:43 UTC, bbedigi approved these changes

2024-01-11 09:44 UTC, leon-thorsell-simonsen approved these changes

2024-01-11 09:45 UTC, merged