footer config update
Digizuite/configurations pull request #315
Opened 2024-02-08 08:07 UTC by andrii-moskalenko

2024-02-09 11:32 UTC, Poiar requested changes

2024-02-09 15:00 UTC, andrii-moskalenko commented
@Poiar I've added settings menu option 'Page footer'

2024-02-09 15:27 UTC, Poiar requested changes

2024-02-09 15:27 UTC, Poiar commented on MM/5.10.0/config/media_manager_5/labels/Settings.dcl
> +      default_translation = '{languageId, select, 1 {Dansk } 3 {Engelsk } other {}}Footer text'
```suggestion
      default_translation = '{languageId, select, 1 {Dansk footer} 3 {Engelsk footer} other {Footer}} text'
```

2024-02-09 15:27 UTC, Poiar commented on MM/5.10.0/config/media_manager_5/labels/Settings.dcl
> +      default_translation = '{languageId, select, 1 {Danish f} 3 {English f} other {F}}ooter text'
```suggestion
      default_translation = '{languageId, select, 1 {Danish footer} 3 {English footer} other {Footer}} text'
```

2024-02-09 15:28 UTC, Poiar requested changes

2024-02-09 15:28 UTC, Poiar commented on MM/5.10.0/config/media_manager_5/labels/Settings.dcl
> +      default_translation = 'Page footer'
```suggestion
      default_translation = 'Side-footer'
```

2024-02-12 14:41 UTC, Poiar approved these changes

2024-02-12 14:54 UTC, merged