task/MM5-5833 Added and updated labels
Digizuite/configurations pull request #321
Opened 2024-02-14 13:55 UTC by Svane20

2024-02-14 14:15 UTC, Poiar requested changes

2024-02-14 14:15 UTC, Poiar commented on MM/5.10.0/config/media_manager_5/labels/Duplicate Assets.dcl
> +      default_translation = 'Do for all'
```suggestion
      default_translation = 'Repeat this action for all uploads with only one match'
```

2024-02-14 14:15 UTC, Poiar commented on MM/5.10.0/config/media_manager_5/labels/Duplicate Assets.dcl
> +      default_translation = 'Gør for alle'
```suggestion
      default_translation = 'Gentag denne handling for alle uploads med kun ét match'
```

2024-02-14 14:15 UTC, Poiar commented on MM/5.9.0/config/media_manager_5/labels/Duplicate Assets.dcl
> +      default_translation = 'Do for all'
```suggestion
      default_translation = 'Gentag denne handling for alle uploads med kun ét match'
```

2024-02-14 14:15 UTC, Poiar commented on MM/5.9.0/config/media_manager_5/labels/Duplicate Assets.dcl
> +      default_translation = 'Gør for alle'
```suggestion
      default_translation = 'Gentag denne handling for alle uploads med kun ét match'
```

2024-02-15 10:34 UTC, Svane20 commented on MM/5.10.0/config/media_manager_5/labels/Duplicate Assets.dcl
> +      default_translation = 'Do for all'
I fear that the name is too long

2024-02-15 10:37 UTC, Svane20 commented on MM/5.10.0/config/media_manager_5/labels/Duplicate Assets.dcl
> +      default_translation = 'Do for all'
Repeat this action for all uploads

2024-02-15 10:37 UTC, Svane20 commented on MM/5.9.0/config/media_manager_5/labels/Duplicate Assets.dcl
> +      default_translation = 'Do for all'
Repeat this action for all uploads

2024-02-15 10:37 UTC, Svane20 commented on MM/5.9.0/config/media_manager_5/labels/Duplicate Assets.dcl
> +      default_translation = 'Gør for alle'
Gentag denne handling for alle uploads

2024-02-15 10:37 UTC, Svane20 commented on MM/5.10.0/config/media_manager_5/labels/Duplicate Assets.dcl
> +      default_translation = 'Gør for alle'
Gentag denne handling for alle uploads

2024-02-16 07:21 UTC, Poiar requested changes

2024-02-16 07:21 UTC, Poiar commented on MM/5.10.0/config/media_manager_5/labels/Duplicate Assets.dcl
> +      default_translation = 'Do for all'
```suggestion
      default_translation = 'Repeat this action for all uploads'
```

2024-02-16 07:21 UTC, Poiar commented on MM/5.10.0/config/media_manager_5/labels/Duplicate Assets.dcl
> +      default_translation = 'Gør for alle'
```suggestion
      default_translation = 'Gentag denne handling for alle uploads'
```

2024-02-16 07:21 UTC, Poiar commented on MM/5.9.0/config/media_manager_5/labels/Duplicate Assets.dcl
> +      default_translation = 'Do for all'
```suggestion
      default_translation = 'Repeat this action for all uploads'
```

2024-02-16 07:21 UTC, Poiar commented on MM/5.9.0/config/media_manager_5/labels/Duplicate Assets.dcl
> +      default_translation = 'Gør for alle'
```suggestion
      default_translation = 'Repeat this action for all uploads'
```

2024-02-16 11:30 UTC, Poiar requested changes

2024-02-16 11:30 UTC, Poiar commented on MM/5.10.0/config/media_manager_5/labels/Duplicate Assets.dcl
> +      default_translation = 'Do for all'
```suggestion
      default_translation = 'Repeat action for all'
```

2024-02-16 11:30 UTC, Poiar commented on MM/5.9.0/config/media_manager_5/labels/Duplicate Assets.dcl
> +      default_translation = 'Do for all'
```suggestion
      default_translation = 'Repeat action for all''
```

2024-02-16 11:30 UTC, Poiar commented on MM/5.10.0/config/media_manager_5/labels/Duplicate Assets.dcl
> +      default_translation = 'Gør for alle'
```suggestion
      default_translation = 'Gentag handling for alle'
```

2024-02-16 11:30 UTC, Poiar commented on MM/5.9.0/config/media_manager_5/labels/Duplicate Assets.dcl
> +      default_translation = 'Gør for alle'
```suggestion
      default_translation = 'Gentag handling for alle'
```

2024-02-16 11:36 UTC, Poiar approved these changes

2024-02-16 11:38 UTC, merged