MM5-6146 updated/created asset audit trail and system audit trail
Digizuite/configurations pull request #456
Opened 2024-06-14 13:04 UTC by YevheniiKravchenko

[MM5-6146](https://digizuite.atlassian.net/browse/MM5-6146): updated/created asset audit trail and system audit trail

2024-06-21 10:31 UTC, bbedigi commented on MM/6.0.0/config/media_manager_5/labels/Administration.dcl
> +      default_translation = 'System historik'
You move this to the 6.1.0 directory now

2024-06-21 12:13 UTC, Poiar requested changes

2024-06-21 12:13 UTC, Poiar commented on MM/6.1.0/config/media_manager_5/labels/Administration.dcl
> +      default_translation = 'Asset historik'
```suggestion
      default_translation = 'Asset-historik'
```

2024-06-21 12:13 UTC, Poiar commented on MM/6.1.0/config/media_manager_5/labels/Administration.dcl
> +      default_translation = 'System historik'
```suggestion
      default_translation = 'System-historik'
```

2024-06-25 07:35 UTC, Poiar approved these changes

2024-06-25 07:46 UTC, merged