MM5-6499 added translations to delete and reassign modal
Digizuite/configurations pull request #582
Opened 2024-10-30 13:59 UTC by YevheniiKravchenko

2024-10-30 14:57 UTC, Poiar commented
![ms-teams_afKzioztyo](https://github.com/user-attachments/assets/732034dc-4a52-4d8c-a69b-bfbdeeb09c75)

2024-10-30 15:06 UTC, Poiar requested changes

2024-10-30 15:06 UTC, Poiar commented on MM/6.2.0/config/media_manager_5/labels/Administration.dcl
> +      default_translation = 'Do you want to reassign these assets?'
```suggestion
      default_translation = 'Move the assets to this category:'
```

2024-11-11 13:10 UTC, bbedigi commented
I suggest a combination
<img width="461" alt="Screenshot 2024-11-11 at 14 08 55" src="https://github.com/user-attachments/assets/30c4189c-4302-4e1f-a806-9ad6c8fd8cbc">

2024-11-12 09:38 UTC, Poiar requested changes

2024-11-12 09:38 UTC, Poiar commented on MM/6.2.0/config/media_manager_5/labels/Administration.dcl
> +      default_translation = 'Move the assets to this category:'
```suggestion
      default_translation = 'Assign the assets to this category:'
```

2024-11-12 09:38 UTC, Poiar commented on MM/6.2.0/config/media_manager_5/labels/Administration.dcl
> +      default_translation = 'Reassign assets and delete category'
```suggestion
      default_translation = 'Reassign assets and delete category'
```

2024-11-12 09:38 UTC, Poiar commented on MM/6.2.0/config/media_manager_5/labels/Administration.dcl
> +      default_translation = 'Gentildel aktiver og slet kategori'
```suggestion
      default_translation = 'Flyt assetsne og slet kategori'
```

2024-11-12 09:41 UTC, bbedigi commented on MM/6.2.0/config/media_manager_5/labels/Administration.dcl
> +Vælg en ny kategori for assetsne, for at fortsætte.'
```suggestion
      default_translation = 'Et eller flere assets er tildelt kategorien \'{{name}}\' eller dens underkategorier.'
```

2024-11-12 10:01 UTC, bbedigi approved these changes

2024-11-12 10:02 UTC, Poiar approved these changes

2024-11-12 10:02 UTC, merged