task/MM5-6599: Admin UI for asset relation types
Digizuite/configurations pull request #607
Opened 2024-11-29 12:03 UTC by IgorDemo

https://digizuite.atlassian.net/browse/MM5-6599

2024-12-04 15:16 UTC, bbedigi commented
@TobiasWolters do you want to add some descriptive tooltips the various inputs? 
Igor has added tooltip, but they are repeating the header at the moment.
![Screenshot 2024-12-04 at 16 15 25](https://github.com/user-attachments/assets/34c13a82-fe75-4010-8092-11d5c2599a07)

2024-12-05 06:43 UTC, TobiasWolters commented
@bbedigi Sure. Most of the descriptions can be taken directly from our API documentation 😉 
- `Block publishing`: If enabled, the target asset of this relation can not be published to any channels at all.
- `Inherit channel folders`: If enabled, the target asset of this relation will inherit the channel folders of the source asset.
- Read/write: Controls what parts of item security the target asset of this relation inherits from the source asset.
- `Inherit soft delete`: If enabled, the target asset of this relation will automatically be soft deleted when the source asset is soft deleted.
- `Inherit hard delete`: If enabled, the target asset of this relation will automatically be hard deleted when the source asset is hard deleted. 
- `Available during transcode`: If enabled, the target asset of this relation will be made available when creating renditions of the source asset. Note that this is only required and supported by some transcoders.
- `Override format purposes`: The different format purposes where the source asset should use the rendition of the target asset.

2024-12-05 11:10 UTC, Poiar requested changes

2024-12-05 11:10 UTC, Poiar commented on MM/6.2.0/config/media_manager_5/labels/Administration.dcl
> +      default_translation = 'Tilsidesæt formatformål'
```suggestion
      default_translation = 'Overskriv format-formål'
```

2024-12-05 11:10 UTC, Poiar commented on MM/6.2.0/config/media_manager_5/labels/Administration.dcl
> +      default_translation = 'De forskellige formatformål, hvor kildeaktivet skal bruge gengivelsen af target-asset'
```suggestion
      default_translation = 'De forskellige formatformål, hvor kilde-assettet skal bruge renditionen fra mål-assetet'
```

2024-12-05 11:10 UTC, Poiar commented on MM/6.2.0/config/media_manager_5/labels/Administration.dcl
> +      default_translation = 'Asset-relationstype blev ikke slettet'
```suggestion
      default_translation = 'Asset-relationstypen blev ikke slettet'
```

2024-12-05 11:10 UTC, Poiar commented on MM/6.2.0/config/media_manager_5/labels/Administration.dcl
> +      default_translation = 'Asset-relationstype blev gemt'
```suggestion
      default_translation = 'Asset-relationstypen blev gemt'
```

2024-12-05 11:10 UTC, Poiar commented on MM/6.2.0/config/media_manager_5/labels/Administration.dcl
> +      default_translation = 'Asset-relationstype blev ikke gemt'
```suggestion
      default_translation = 'Asset-relationstypen blev ikke gemt'
```

2024-12-05 12:05 UTC, bbedigi commented on MM/6.2.0/config/media_manager_5/labels/Administration.dcl
> +      default_translation = 'Primary to secondary label'
How about 'Label on source asset'

2024-12-05 12:05 UTC, bbedigi commented on MM/6.2.0/config/media_manager_5/labels/Administration.dcl
> +      default_translation = 'Primær til sekundær etiket'
'Label on target asset'

2024-12-05 13:27 UTC, Poiar requested changes
Added new suggestions

2024-12-05 13:29 UTC, Poiar requested changes

2024-12-05 13:29 UTC, Poiar commented on MM/6.2.0/config/media_manager_5/labels/Administration.dcl
> +      default_translation = 'Target →  source label'
```suggestion
      default_translation = 'Target → source label'
```

2024-12-05 13:29 UTC, Poiar commented on MM/6.2.0/config/media_manager_5/labels/Administration.dcl
> +      default_translation = 'Source → target label'
```suggestion
      default_translation = 'Mål → kilde label'
```

2024-12-05 13:32 UTC, Poiar approved these changes

2024-12-05 13:37 UTC, merged